image: fedora:rawhide

variables:
  DEPENDENCIES:
    gcc
    gtk-doc
    make
    autoconf
    autoconf-archive
    automake
    gettext-devel
    libtool
    chrpath
    mesa-dri-drivers
    mesa-libEGL-devel
    xorg-x11-server-Xvfb
    pkgconfig(cairo)
    pkgconfig(gbm)
    pkgconfig(gdk-pixbuf-2.0)
    pkgconfig(gl)
    pkgconfig(glib-2.0)
    pkgconfig(gobject-introspection-1.0)
    pkgconfig(gtk-doc)
    pkgconfig(libdrm)
    pkgconfig(pango)
    pkgconfig(xcomposite)
    pkgconfig(xdamage)
    pkgconfig(xext)
    pkgconfig(xfixes)
    pkgconfig(xrandr)
    pkgconfig(wayland-server)
    pkgconfig(wayland-client)
    pkgconfig(wayland-cursor)
    pkgconfig(wayland-egl)
    pkgconfig(xkbcommon)
  COGL_RENDERER: "glx"

build_stable:
  before_script:
    - dnf upgrade -y --nogpgcheck fedora-release fedora-repos*
    - dnf update -y && dnf install -y $DEPENDENCIES
  script:
    - ./autogen.sh --disable-dependency-tracking --disable-gtk-doc
    - make
#   Disable the test suite; it completely fails on CI
#    - xvfb-run -a -s "-screen 0 1024x768x24" make check
    - make install

