image: fedora:rawhide

variables:
  DEPENDENCIES:
    gcc
    gtk-doc
    make
    autoconf
    autoconf-archive
    automake
    gettext-devel
    libtool
    chrpath
    pkgconfig(cairo)
    mesa-libEGL-devel
    pkgconfig(gbm)
    pkgconfig(gdk-pixbuf-2.0)
    pkgconfig(gl)
    pkgconfig(glib-2.0)
    pkgconfig(gobject-introspection-1.0)
    pkgconfig(gtk-doc)
    pkgconfig(libdrm)
    pkgconfig(pango)
    pkgconfig(xcomposite)
    pkgconfig(xdamage)
    pkgconfig(xext)
    pkgconfig(xfixes)
    pkgconfig(xrandr)
    pkgconfig(wayland-server)
    pkgconfig(wayland-client)
    pkgconfig(wayland-cursor)
    pkgconfig(wayland-egl)
    pkgconfig(xkbcommon)

build_stable:
  before_script:
    - dnf upgrade -y --nogpgcheck fedora-release fedora-repos*
    - dnf update -y && dnf install -y $DEPENDENCIES
  script:
    - CPPFLAGS='-D_FORTIFY_SOURCE=2' ./autogen.sh --disable-dependency-tracking --enable-gtk-doc --enable-gtk-tests
    - make
    - make check
    - make install

